[theme]
# Primary accent color for interactive elements.
primaryColor = "transparent"

# Background color for the main content area.
backgroundColor = "transparent"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#d2d3d3"

# Color used for almost all text.
textColor = "#000"